CREATE SEQUENCE hibernate_sequence
	START WITH 1 INCREMENT 1;
	
CREATE TABLE online_order(
	id BIGINT NOT NULL PRIMARY KEY,
	date TIMESTAMP NOT NULL,
	amount DECIMAL NOT NULL,
	paid BOOLEAN NOT NULL
);

CREATE TABLE PAYMENT(
    id BIGINT NOT NULL PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    credit_card_number VARCHAR(16) REFERENCES orders(id)
);